import type { Metadata } from "next";
import "./styles/global/globals.css"

export const metadata: Metadata = {
  title: "Climate System",
  description: "Generated by Thiago",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <head>
        <link rel="icon" href="/icon/favicon.png" />
      </head>
      <body>
        {children}
      </body>
    </html>
  );
}
